development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: partiude
  pool: 5
  username: partiude
  password: 123

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
